# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 529)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 400))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 1000))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(1000, 1000))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Play = QtWidgets.QWidget()
        self.Play.setObjectName("Play")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Play)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_6 = QtWidgets.QPushButton(self.Play)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.pushButton_4 = QtWidgets.QPushButton(self.Play)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.gridLayout_5.addLayout(self.horizontalLayout, 6, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 249, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 5, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.Play)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.spinBox = QtWidgets.QSpinBox(self.Play)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.label_7 = QtWidgets.QLabel(self.Play)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.spinBox_2 = QtWidgets.QSpinBox(self.Play)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_2.addWidget(self.spinBox_2)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.Play)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_5.addWidget(self.pushButton_8, 4, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.Play)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.textEdit = QtWidgets.QTextEdit(self.Play)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMaximumSize(QtCore.QSize(50, 30))
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_3.addWidget(self.textEdit)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.Play)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_5.addWidget(self.pushButton_7, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.Play)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 1, 1, 1)
        self.mplwindow_3 = QtWidgets.QWidget(self.Play)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwindow_3.sizePolicy().hasHeightForWidth())
        self.mplwindow_3.setSizePolicy(sizePolicy)
        self.mplwindow_3.setToolTipDuration(-22)
        self.mplwindow_3.setObjectName("mplwindow_3")
        self.mplvl_3 = QtWidgets.QVBoxLayout(self.mplwindow_3)
        self.mplvl_3.setObjectName("mplvl_3")
        self.gridLayout_5.addWidget(self.mplwindow_3, 0, 0, 7, 1)
        self.stackedWidget.addWidget(self.Play)
        self.Viewer = QtWidgets.QWidget()
        self.Viewer.setObjectName("Viewer")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Viewer)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.mplwindow_2 = QtWidgets.QWidget(self.Viewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwindow_2.sizePolicy().hasHeightForWidth())
        self.mplwindow_2.setSizePolicy(sizePolicy)
        self.mplwindow_2.setToolTipDuration(-22)
        self.mplwindow_2.setObjectName("mplwindow_2")
        self.mplvl_2 = QtWidgets.QVBoxLayout(self.mplwindow_2)
        self.mplvl_2.setObjectName("mplvl_2")
        self.gridLayout_4.addWidget(self.mplwindow_2, 0, 0, 3, 1)
        self.checkBox = QtWidgets.QCheckBox(self.Viewer)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_4.addWidget(self.checkBox, 0, 1, 1, 2, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.Viewer)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 1, 1, 2, QtCore.Qt.AlignHCenter)
        self.BackButton = QtWidgets.QPushButton(self.Viewer)
        self.BackButton.setObjectName("BackButton")
        self.gridLayout_4.addWidget(self.BackButton, 2, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.Viewer)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 2, 2, 1, 1)
        self.mplwindow = QtWidgets.QWidget(self.Viewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwindow.sizePolicy().hasHeightForWidth())
        self.mplwindow.setSizePolicy(sizePolicy)
        self.mplwindow.setToolTipDuration(-22)
        self.mplwindow.setObjectName("mplwindow")
        self.mplvl = QtWidgets.QVBoxLayout(self.mplwindow)
        self.mplvl.setObjectName("mplvl")
        self.gridLayout_4.addWidget(self.mplwindow, 3, 0, 3, 1)
        self.label_3 = QtWidgets.QLabel(self.Viewer)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 3, 1, 1, 2)
        self.mplfigs = QtWidgets.QListWidget(self.Viewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplfigs.sizePolicy().hasHeightForWidth())
        self.mplfigs.setSizePolicy(sizePolicy)
        self.mplfigs.setMaximumSize(QtCore.QSize(200, 16777215))
        self.mplfigs.setObjectName("mplfigs")
        self.gridLayout_4.addWidget(self.mplfigs, 4, 1, 1, 2)
        self.pushButton_5 = QtWidgets.QPushButton(self.Viewer)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_4.addWidget(self.pushButton_5, 5, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.Viewer)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_4.addWidget(self.pushButton_3, 5, 2, 1, 1)
        self.stackedWidget.addWidget(self.Viewer)
        self.SavedGames = QtWidgets.QWidget()
        self.SavedGames.setObjectName("SavedGames")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.SavedGames)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.SavedGames)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.Autosave = QtWidgets.QPushButton(self.SavedGames)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Autosave.sizePolicy().hasHeightForWidth())
        self.Autosave.setSizePolicy(sizePolicy)
        self.Autosave.setObjectName("Autosave")
        self.gridLayout_3.addWidget(self.Autosave, 1, 0, 1, 1)
        self.Save1 = QtWidgets.QPushButton(self.SavedGames)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Save1.sizePolicy().hasHeightForWidth())
        self.Save1.setSizePolicy(sizePolicy)
        self.Save1.setObjectName("Save1")
        self.gridLayout_3.addWidget(self.Save1, 2, 0, 1, 1)
        self.Save2 = QtWidgets.QPushButton(self.SavedGames)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Save2.sizePolicy().hasHeightForWidth())
        self.Save2.setSizePolicy(sizePolicy)
        self.Save2.setObjectName("Save2")
        self.gridLayout_3.addWidget(self.Save2, 3, 0, 1, 1)
        self.Save3 = QtWidgets.QPushButton(self.SavedGames)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Save3.sizePolicy().hasHeightForWidth())
        self.Save3.setSizePolicy(sizePolicy)
        self.Save3.setObjectName("Save3")
        self.gridLayout_3.addWidget(self.Save3, 4, 0, 1, 1)
        self.stackedWidget.addWidget(self.SavedGames)
        self.MainMenu = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainMenu.sizePolicy().hasHeightForWidth())
        self.MainMenu.setSizePolicy(sizePolicy)
        self.MainMenu.setObjectName("MainMenu")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.MainMenu)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.MainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 2)
        self.NewGame = QtWidgets.QPushButton(self.MainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NewGame.sizePolicy().hasHeightForWidth())
        self.NewGame.setSizePolicy(sizePolicy)
        self.NewGame.setMinimumSize(QtCore.QSize(0, 0))
        self.NewGame.setMaximumSize(QtCore.QSize(1000, 100))
        self.NewGame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.NewGame.setObjectName("NewGame")
        self.gridLayout_2.addWidget(self.NewGame, 1, 1, 1, 2)
        self.Continue = QtWidgets.QPushButton(self.MainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Continue.sizePolicy().hasHeightForWidth())
        self.Continue.setSizePolicy(sizePolicy)
        self.Continue.setMaximumSize(QtCore.QSize(1000, 100))
        self.Continue.setObjectName("Continue")
        self.gridLayout_2.addWidget(self.Continue, 2, 1, 1, 2)
        self.Records = QtWidgets.QPushButton(self.MainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Records.sizePolicy().hasHeightForWidth())
        self.Records.setSizePolicy(sizePolicy)
        self.Records.setMaximumSize(QtCore.QSize(1000, 100))
        self.Records.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Records.setObjectName("Records")
        self.gridLayout_2.addWidget(self.Records, 3, 1, 1, 2)
        self.Options = QtWidgets.QPushButton(self.MainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Options.sizePolicy().hasHeightForWidth())
        self.Options.setSizePolicy(sizePolicy)
        self.Options.setMaximumSize(QtCore.QSize(500, 100))
        self.Options.setObjectName("Options")
        self.gridLayout_2.addWidget(self.Options, 4, 1, 1, 1)
        self.QuitGame = QtWidgets.QPushButton(self.MainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QuitGame.sizePolicy().hasHeightForWidth())
        self.QuitGame.setSizePolicy(sizePolicy)
        self.QuitGame.setMaximumSize(QtCore.QSize(500, 100))
        self.QuitGame.setObjectName("QuitGame")
        self.gridLayout_2.addWidget(self.QuitGame, 4, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(265, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 5, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(265, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 5, 3, 1, 1)
        self.stackedWidget.addWidget(self.MainMenu)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        self.QuitGame.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_6.setText(_translate("MainWindow", "Save"))
        self.pushButton_4.setText(_translate("MainWindow", "Main Menu"))
        self.label_6.setText(_translate("MainWindow", "x :"))
        self.label_7.setText(_translate("MainWindow", "y :"))
        self.pushButton_8.setText(_translate("MainWindow", "Undo"))
        self.label_5.setText(_translate("MainWindow", "Next move by:"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Red</p></body></html>"))
        self.pushButton_7.setText(_translate("MainWindow", "Move"))
        self.label_8.setText(_translate("MainWindow", "PvP Mode"))
        self.checkBox.setText(_translate("MainWindow", "Toggle Overlay"))
        self.label_4.setText(_translate("MainWindow", "Step Through Game"))
        self.BackButton.setText(_translate("MainWindow", "Backwards"))
        self.pushButton_2.setText(_translate("MainWindow", "Forwards"))
        self.label_3.setText(_translate("MainWindow", "Recorded Games"))
        self.pushButton_5.setText(_translate("MainWindow", "Play Current"))
        self.pushButton_3.setText(_translate("MainWindow", "Main Menu"))
        self.label_2.setText(_translate("MainWindow", "Saved Games"))
        self.Autosave.setText(_translate("MainWindow", "Autosave"))
        self.Save1.setText(_translate("MainWindow", "Save Slot 1"))
        self.Save2.setText(_translate("MainWindow", "Save Slot 2"))
        self.Save3.setText(_translate("MainWindow", "Save Slot 3"))
        self.label.setText(_translate("MainWindow", "Welcome to FIAR"))
        self.NewGame.setText(_translate("MainWindow", "New Game"))
        self.Continue.setText(_translate("MainWindow", "Continue"))
        self.Records.setText(_translate("MainWindow", "Records"))
        self.Options.setText(_translate("MainWindow", "Options"))
        self.QuitGame.setText(_translate("MainWindow", "Quit Game"))

