# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewGame.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(239, 319)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.PvPFirstSelector = QtWidgets.QComboBox(self.page)
        self.PvPFirstSelector.setObjectName("PvPFirstSelector")
        self.PvPFirstSelector.addItem("")
        self.PvPFirstSelector.addItem("")
        self.gridLayout_3.addWidget(self.PvPFirstSelector, 0, 1, 1, 1, QtCore.Qt.AlignTop)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.AIColorSelector = QtWidgets.QComboBox(self.page_2)
        self.AIColorSelector.setObjectName("AIColorSelector")
        self.AIColorSelector.addItem("")
        self.AIColorSelector.addItem("")
        self.gridLayout.addWidget(self.AIColorSelector, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.PvAIFirstSelector = QtWidgets.QComboBox(self.page_2)
        self.PvAIFirstSelector.setObjectName("PvAIFirstSelector")
        self.PvAIFirstSelector.addItem("")
        self.PvAIFirstSelector.addItem("")
        self.gridLayout.addWidget(self.PvAIFirstSelector, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_2.addWidget(self.stackedWidget, 1, 0, 1, 2)
        self.ModeSelector = QtWidgets.QComboBox(Dialog)
        self.ModeSelector.setObjectName("ModeSelector")
        self.ModeSelector.addItem("")
        self.ModeSelector.addItem("")
        self.gridLayout_2.addWidget(self.ModeSelector, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 2, 0, 1, 1)
        self.NewGame_Cancel = QtWidgets.QPushButton(Dialog)
        self.NewGame_Cancel.setObjectName("NewGame_Cancel")
        self.gridLayout_2.addWidget(self.NewGame_Cancel, 2, 1, 1, 1)
        self.label.setBuddy(self.ModeSelector)
        self.label_2.setBuddy(self.PvPFirstSelector)
        self.label_3.setBuddy(self.AIColorSelector)
        self.label_4.setBuddy(self.PvAIFirstSelector)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        self.ModeSelector.activated['int'].connect(self.stackedWidget.setCurrentIndex)
        self.NewGame_Cancel.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Game Mode:"))
        self.PvPFirstSelector.setItemText(0, _translate("Dialog", "Red"))
        self.PvPFirstSelector.setItemText(1, _translate("Dialog", "Black"))
        self.label_2.setText(_translate("Dialog", "First Player:"))
        self.label_3.setText(_translate("Dialog", "AI Color:"))
        self.AIColorSelector.setItemText(0, _translate("Dialog", "Red"))
        self.AIColorSelector.setItemText(1, _translate("Dialog", "Black"))
        self.label_4.setText(_translate("Dialog", "First Player"))
        self.PvAIFirstSelector.setItemText(0, _translate("Dialog", "Red"))
        self.PvAIFirstSelector.setItemText(1, _translate("Dialog", "Black"))
        self.ModeSelector.setItemText(0, _translate("Dialog", "PvP"))
        self.ModeSelector.setItemText(1, _translate("Dialog", "PvAI"))
        self.pushButton.setText(_translate("Dialog", "Play"))
        self.NewGame_Cancel.setText(_translate("Dialog", "Cancel"))

